version: "3.1"

services:
  wordpress:
    container_name: "wordpress"
    image: wordpress:latest
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    container_name: "mysql"
    image: mariadb:latest
    restart: unless-stopped

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    depends_on:
      - mysql
    restart: unless-stopped
