version: "3.1"

services:
  wordpress:
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: underscored
    volumes:
      - ${HOME}/wordpress:/var/www/html
      - ./theme/:/var/www/html/wp-content/themes/sobol

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: underscored
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${HOME}/data/:/var/lib/mysql

  phpmyadmin:
    ports:
      - 3001:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
